# Generated by Django 5.0.6 on 2024-05-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_room_code_alter_room_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
